export const mockBrands = [
  {
    id: 'br_001',
    name: 'TechFlow Pro',
    status: 'active',
    ambassadors: 12,
    campaigns: 8,
    revenue: '$48,500',
    lastActive: '2025-03-08',
    tier: 'enterprise',
  },
  {
    id: 'br_002',
    name: 'GrowthHub',
    status: 'active',
    ambassadors: 8,
    campaigns: 5,
    revenue: '$32,200',
    lastActive: '2025-03-07',
    tier: 'professional',
  },
  {
    id: 'br_003',
    name: 'CreativeStudio',
    status: 'inactive',
    ambassadors: 3,
    campaigns: 2,
    revenue: '$8,900',
    lastActive: '2025-02-28',
    tier: 'starter',
  },
  {
    id: 'br_004',
    name: 'DataViz Analytics',
    status: 'active',
    ambassadors: 15,
    campaigns: 11,
    revenue: '$67,300',
    lastActive: '2025-03-08',
    tier: 'enterprise',
  },
  {
    id: 'br_005',
    name: 'CloudScale',
    status: 'active',
    ambassadors: 6,
    campaigns: 4,
    revenue: '$24,100',
    lastActive: '2025-03-06',
    tier: 'professional',
  },
];

export const mockCampaigns = [
  {
    id: 'camp_001',
    name: 'Spring Launch 2025',
    brand: 'TechFlow Pro',
    status: 'running',
    progress: 78,
    kits: 24,
    createdAt: '2025-01-15',
    deadline: '2025-04-15',
  },
  {
    id: 'camp_002',
    name: 'Summer Collection',
    brand: 'GrowthHub',
    status: 'planning',
    progress: 12,
    kits: 5,
    createdAt: '2025-03-01',
    deadline: '2025-06-01',
  },
  {
    id: 'camp_003',
    name: 'Q1 Performance Push',
    brand: 'DataViz Analytics',
    status: 'running',
    progress: 92,
    kits: 48,
    createdAt: '2024-12-01',
    deadline: '2025-03-31',
  },
  {
    id: 'camp_004',
    name: 'Holiday Season',
    brand: 'CreativeStudio',
    status: 'completed',
    progress: 100,
    kits: 15,
    createdAt: '2024-10-01',
    deadline: '2024-12-31',
  },
  {
    id: 'camp_005',
    name: 'Winter Warmup',
    brand: 'CloudScale',
    status: 'running',
    progress: 45,
    kits: 12,
    createdAt: '2025-01-20',
    deadline: '2025-03-20',
  },
];

export const mockGenerationQueue = [
  {
    id: 'gen_001',
    campaign: 'Spring Launch 2025',
    type: 'product_image',
    status: 'completed',
    provider: 'OpenAI',
    tokens: 2500,
    cost: '$0.85',
    queuedAt: '2025-03-08 14:23',
    completedAt: '2025-03-08 14:27',
  },
  {
    id: 'gen_002',
    campaign: 'Q1 Performance Push',
    type: 'social_caption',
    status: 'processing',
    provider: 'Anthropic',
    tokens: 450,
    cost: '$0.12',
    queuedAt: '2025-03-08 15:45',
    completedAt: null,
  },
  {
    id: 'gen_003',
    campaign: 'Spring Launch 2025',
    type: 'blog_post',
    status: 'queued',
    provider: 'OpenAI',
    tokens: 3200,
    cost: '$1.08',
    queuedAt: '2025-03-08 16:10',
    completedAt: null,
  },
  {
    id: 'gen_004',
    campaign: 'Winter Warmup',
    type: 'email_copy',
    status: 'completed',
    provider: 'Anthropic',
    tokens: 1200,
    cost: '$0.32',
    queuedAt: '2025-03-08 10:15',
    completedAt: '2025-03-08 10:18',
  },
  {
    id: 'gen_005',
    campaign: 'Summer Collection',
    type: 'description',
    status: 'failed',
    provider: 'OpenAI',
    tokens: 0,
    cost: '$0.00',
    queuedAt: '2025-03-08 13:30',
    completedAt: '2025-03-08 13:32',
  },
];

export const mockAmbassadors = [
  {
    id: 'amb_001',
    name: 'Sarah Chen',
    email: 'sarah.chen@example.com',
    brand: 'TechFlow Pro',
    status: 'active',
    followers: '125K',
    joined: '2024-06-15',
  },
  {
    id: 'amb_002',
    name: 'Marcus Johnson',
    email: 'marcus.j@example.com',
    brand: 'DataViz Analytics',
    status: 'active',
    followers: '89K',
    joined: '2024-08-20',
  },
  {
    id: 'amb_003',
    name: 'Elena Rodriguez',
    email: 'elena.r@example.com',
    brand: 'GrowthHub',
    status: 'inactive',
    followers: '156K',
    joined: '2024-05-10',
  },
  {
    id: 'amb_004',
    name: 'David Park',
    email: 'david.park@example.com',
    brand: 'TechFlow Pro',
    status: 'active',
    followers: '234K',
    joined: '2024-03-01',
  },
  {
    id: 'amb_005',
    name: 'Lisa Anderson',
    email: 'lisa.a@example.com',
    brand: 'CloudScale',
    status: 'active',
    followers: '78K',
    joined: '2024-11-05',
  },
];

export const mockAnalytics = {
  overview: {
    totalCampaigns: 47,
    activeCampaigns: 23,
    totalAmbassadors: 68,
    totalRevenue: '$212,000',
    monthlyGrowth: '+12.5%',
    aiGenerations: '1,847',
    tokensUsed: '2,847,500',
    costPerThousandTokens: '$0.34',
  },
  campaignActivity: [
    { date: 'Mon', campaigns: 4, completions: 8, failed: 1 },
    { date: 'Tue', campaigns: 5, completions: 12, failed: 2 },
    { date: 'Wed', campaigns: 6, completions: 15, failed: 0 },
    { date: 'Thu', campaigns: 4, completions: 10, failed: 1 },
    { date: 'Fri', campaigns: 7, completions: 18, failed: 1 },
    { date: 'Sat', campaigns: 3, completions: 5, failed: 0 },
    { date: 'Sun', campaigns: 2, completions: 3, failed: 0 },
  ],
  providerCosts: [
    { name: 'OpenAI', value: 45, percentage: 45 },
    { name: 'Anthropic', value: 35, percentage: 35 },
    { name: 'Google', value: 15, percentage: 15 },
    { name: 'Others', value: 5, percentage: 5 },
  ],
  generationVolume: [
    { type: 'Images', count: 324 },
    { type: 'Text', count: 892 },
    { type: 'Video', count: 156 },
    { type: 'Audio', count: 475 },
  ],
};

export const mockAuditLogs = [
  {
    id: 'log_001',
    user: 'admin@sirz.com',
    action: 'Created campaign',
    resource: 'Spring Launch 2025',
    timestamp: '2025-03-08 16:45:23',
    status: 'success',
  },
  {
    id: 'log_002',
    user: 'brand@techflow.com',
    action: 'Updated brand settings',
    resource: 'TechFlow Pro',
    timestamp: '2025-03-08 15:32:11',
    status: 'success',
  },
  {
    id: 'log_003',
    user: 'admin@sirz.com',
    action: 'Deleted old campaign',
    resource: 'Archived Q4 2024',
    timestamp: '2025-03-08 14:20:45',
    status: 'success',
  },
  {
    id: 'log_004',
    user: 'unknown',
    action: 'Failed login attempt',
    resource: 'Authentication',
    timestamp: '2025-03-08 13:15:32',
    status: 'failure',
  },
];

export const mockTeamMembers = [
  {
    id: 'tm_001',
    name: 'Alex Johnson',
    email: 'alex.johnson@sirz.com',
    role: 'admin',
    createdAt: '2024-01-15',
    lastActive: '2025-03-08 09:30',
    status: 'active',
  },
  {
    id: 'tm_002',
    name: 'Jordan Smith',
    email: 'jordan.smith@sirz.com',
    role: 'manager',
    createdAt: '2024-03-22',
    lastActive: '2025-03-08 08:15',
    status: 'active',
  },
  {
    id: 'tm_003',
    name: 'Casey Williams',
    email: 'casey.williams@sirz.com',
    role: 'analyst',
    createdAt: '2024-06-10',
    lastActive: '2025-03-07 17:45',
    status: 'active',
  },
  {
    id: 'tm_004',
    name: 'Morgan Brown',
    email: 'morgan.brown@sirz.com',
    role: 'moderator',
    createdAt: '2024-08-05',
    lastActive: '2025-03-08 14:20',
    status: 'active',
  },
  {
    id: 'tm_005',
    name: 'Taylor Davis',
    email: 'taylor.davis@sirz.com',
    role: 'analyst',
    createdAt: '2024-09-18',
    lastActive: '2025-03-06 16:10',
    status: 'active',
  },
  {
    id: 'tm_006',
    name: 'Riley Martinez',
    email: 'riley.martinez@sirz.com',
    role: 'manager',
    createdAt: '2024-11-01',
    lastActive: '2025-02-28 13:05',
    status: 'inactive',
  },
];
